apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-test
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: mysql-test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-test
spec:
  selector:
    matchLabels:
     app: mysql-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-test
    spec:
     containers:
     - image: mysql:5.7
       name: mysql-test
       env:
       - name: MYSQL_ROOT_PASSWORD
         valueFrom:
           secretKeyRef:
             name: mysql-secrets
             key: ROOT_PASSWORD       
       - name: MYSQL_DATABASE
         value: my_db
       - name: MYSQL_USER
         value: db_user
       - name: MYSQL_PASSWORD
         valueFrom:
           secretKeyRef:
             name: mysql-secrets
             key: USER_PASSWORD       
       ports:
       - containerPort: 3306
         name: mysql-test
