apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
     app: mysql8
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql8
    spec:
     containers:
     - image: mysql:8.0
       name: mysql
       env:
       - name: MYSQL_ROOT_PASSWORD
         value: password
       - name: MYSQL_DATABASE
         value: my_db
       - name: MYSQL_USER
         value: db_user
       - name: MYSQL_PASSWORD
         value: password
       ports:
       - containerPort: 3306
         name: mysql8
